# 服务端口
server:
  port: 10082

# dataSource
spring:
  application:
    name: frame-base
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/cache_framework?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: login
    driver-class-name: com.mysql.jdbc.Driver # com.mysql.cj.jdbc.Driver
  # redis配置(非集群)
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # password: login
    pool:
      # 连接池中的最大空闲连接 
      max-idle: 666
      # 连接池中的最小空闲连接 
      min-idle: 8
      # 连接池最大连接数（使用负值表示没有限制） 
      max-active: 888
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 777
    
endpoints:
  enabled: false
  info: 
    enabled: true
  health:
    enabled: true
    